apiVersion: v1
kind: Service
metadata:
  name: dorashop-service
  namespace: dorashop
spec:
  selector:
    app: dorashop-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP